# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_neighborhood_multi_radius <- function(sp, gx, gy, ba, r_values, dist_weighted = FALSE, edge_correction = "none") {
    .Call(`_calba_calculate_neighborhood_multi_radius`, sp, gx, gy, ba, r_values, dist_weighted, edge_correction)
}

calculate_basal_area_simple <- function(sp, gx, gy, ba, r, dist_weighted = FALSE, edge_correction = "none") {
    .Call(`_calba_calculate_basal_area_simple`, sp, gx, gy, ba, r, dist_weighted, edge_correction)
}

calculate_basal_area_decay <- function(mu_values, sp, gx, gy, ba, r, decay_type, edge_correction = "none") {
    .Call(`_calba_calculate_basal_area_decay`, mu_values, sp, gx, gy, ba, r, decay_type, edge_correction)
}

count_total_cpp <- function(gx, gy, r, edge_correction = "none") {
    .Call(`_calba_count_total_cpp`, gx, gy, r, edge_correction)
}

count_con_cpp <- function(sp, gx, gy, r, edge_correction = "none") {
    .Call(`_calba_count_con_cpp`, sp, gx, gy, r, edge_correction)
}

