# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_basal_area_decay <- function(mu_values, data, n_focal, r) {
    .Call(`_calba_calculate_basal_area_decay`, mu_values, data, n_focal, r)
}

calculate_basal_area_simple <- function(data, n_focal, r) {
    .Call(`_calba_calculate_basal_area_simple`, data, n_focal, r)
}

